services:

  user-main-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: 'users-db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    volumes:
      - ./user-main-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"