spring:

  application:
    name: auth-service

  profiles:
    default: default

  datasource:
    username: ${}
    password: ${}
    url: ${}
    hikari:
      maximum-pool-size: ${}
      connection-timeout: ${}

  jpa:
    hibernate:
      ddl-auto: ${}

application:
  jwt:
    secret:
    expiration: ${}

server:
  port: 0
