spring:

  application:
    name: auth-service

  profiles:
    default: default

  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    hikari:
      maximum-pool-size: ${spring.datasource.hikari.maximum-pool-size}
      connection-timeout: ${spring.datasource.hikari.connection-timeout}

  jpa:
    hibernate:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}

server:
  servlet:
    context-path: /auth-server
  port: 0
