spring:

  application:
    name: auth-service

  profiles:
    default: default

  datasource:
    username: ${}
    password: ${}
    url: ${}
    hikari:
      maximum-pool-size: ${}
      connection-timeout: ${}

  jpa:
    hibernate:
      ddl-auto: ${}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${}
    password: ${}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  jwt:
    secret:
    expiration: ${}

server:
  port: 0
